### ISSUE TITLE
Floatovers on icons a top of term info - should work in the same way as float overs on main tool icons.  

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB2#220]
They are currently very slow and use different system.

**Comment by Robbie1977** [comment]
Ref https://github.com/VirtualFlyBrain/geppetto-vfb/issues/441

**Comment by ddelpiano** [comment]
This is already done with [this](https://github.com/openworm/geppetto-client/pull/117) and already part of the geppetto-client development branch.
@dosumis I guess you can see this because I think @Robbie1977 is using a different branch to deploy v2-dev2 in order to have the stackviewer tooltip improvement.
